### ISSUE TITLE
Connection refused error on a Flutter project

### ISSUE THREAD

**Issue by salehahmedZ** [appwrite/sdk-for-dart#2]
Thank you for this amazing project it is going to be huge.

I tried to use the dart library on a Flutter project , the dashboard is working fine 

![](https://i.ibb.co/6D2QDn6/Screen-Shot-2020-04-14-at-1-44-54-AM.png)

but it is not working on flutter side:

here is the code

```dart
import 'package:appwrite/appwrite.dart';

void main() {

  final Client client = Client();

  client.setEndpoint('https://localhost:90/v1').setProject('5e9351e30e481').setSelfSigned();

  final Account account = Account(client);

  account.create(email: 'me@appwrite.io', password: 'password', name: 'My Name');

}
```

and this is the error:

```

E/flutter ( 7039): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 45008
E/flutter ( 7039): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure> 
package:dio/src/dio.dart:869
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #1      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart)
E/flutter ( 7039): #3      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 7039): #4      _FutureListener.handleError  (dart:async/future_impl.dart:159:20)
E/flutter ( 7039): #5      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #6      Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #7      Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #8      _SyncCompleter._completeError  (dart:async/future_impl.dart:58:12)
E/flutter ( 7039): #9      _Completer.completeError  (dart:async/future_impl.dart:30:5)
E/flutter ( 7039): #10     Future.any.<anonymous closure>  (dart:async/future.dart:464:45)
E/flutter ( 7039): #11     _rootRunBinary  (dart:async/zone.dart:1204:38)
E/flutter ( 7039): #12     _CustomZone.runBinary  (dart:async/zone.dart:1093:19)
E/flutter ( 7039): #13     _FutureListener.handleError  (dart:async/future_impl.dart:155:20)
E/flutter ( 7039): #14     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #15     Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #16     Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #17     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 7039): #18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:849
E/flutter ( 7039): #20     DioMixin.checkIfNeedEnqueue 
package:dio/src/dio.dart:1117
E/flutter ( 7039): #21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:846
E/flutter ( 7039): #22     new Future.<anonymous closure>  (dart:async/future.dart:176:37)
E/flutter ( 7039): #23     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter ( 7039): #24     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #25     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 7039): #26     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 7039): #27     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 7039): #28     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #29     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1003:23)
E/flutter ( 7039): #30     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7039): #31     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7039): #32     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7039): #33     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7039):


```

I also generate an Api key and used it but it does not work and prints the same error:

![](https://i.ibb.co/5KBWPjk/Screen-Shot-2020-04-14-at-1-54-24-AM.png)

```dart
import 'package:appwrite/appwrite.dart';

void main() {
  final Client client = Client();

  client.setEndpoint('https://localhost:90/v1')
  .setProject('5e9351e30e481')
  .setKey('c7f7afea3c336ad75b9a2dcf0a91a91c5808cebe601127d154257f0e8d0836b442070dbc9d74c581a828bd1436f738fcd8239f7d5f3c1e3f583227588363cabddb7c9c12d74f1d8187fe533068197cfe631c0d8af4309668a231b208c8a82df9c38c921a8ae3fa93aa42892eb786cc39408dce965f4ade3da26fff21527c5d49')
  .setSelfSigned();

  final Account account = Account(client);

  account.create(email: 'me@appwrite.io', password: 'password', name: 'My Name');

}
```

**Comment by salehahmedZ** [comment]
Tried to install the docker on my server an used the custom domain feature to obtain a TLS and the dashboard works fine with https active, but on the Flutter side is prints the following error:


**before setting an Api Key:**


```
E/flutter ( 7039): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [403]
E/flutter ( 7039): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure> 
package:dio/src/dio.dart:869
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #1      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart)
E/flutter ( 7039): #2      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter ( 7039): #3      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 7039): #4      _FutureListener.handleError  (dart:async/future_impl.dart:159:20)
E/flutter ( 7039): #5      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #6      Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #7      Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #8      _SyncCompleter._completeError  (dart:async/future_impl.dart:58:12)
E/flutter ( 7039): #9      _Completer.completeError  (dart:async/future_impl.dart:30:5)
E/flutter ( 7039): #10     Future.any.<anonymous closure>  (dart:async/future.dart:464:45)
E/flutter ( 7039): #11     _rootRunBinary  (dart:async/zone.dart:1204:38)
E/flutter ( 7039): #12     _CustomZone.runBinary  (dart:async/zone.dart:1093:19)
E/flutter ( 7039): #13     _FutureListener.handleError  (dart:async/future_impl.dart:155:20)
E/flutter ( 7039): #14     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #15     Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #16     Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #17     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 7039): #18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:849
E/flutter ( 7039): #20     DioMixin.checkIfNeedEnqueue 
package:dio/src/dio.dart:1117
E/flutter ( 7039): #21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:846
E/flutter ( 7039): #22     new Future.<anonymous closure>  (dart:async/future.dart:176:37)
E/flutter ( 7039): #23     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter ( 7039): #24     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #25     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 7039): #26     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 7039): #27     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 7039): #28     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #29     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1003:23)
E/flutter ( 7039): #30     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7039): #31     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7039): #32     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7039): #33     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7039):
```



**after setting an Api Key:**




```
E/flutter ( 7039): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [401]
E/flutter ( 7039): #0      DioMixin._request._errorInterceptorWrapper.<anonymous closure> 
package:dio/src/dio.dart:869
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #1      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart)
E/flutter ( 7039): #2      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter ( 7039): #3      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 7039): #4      _FutureListener.handleError  (dart:async/future_impl.dart:159:20)
E/flutter ( 7039): #5      Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #6      Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #7      Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #8      _SyncCompleter._completeError  (dart:async/future_impl.dart:58:12)
E/flutter ( 7039): #9      _Completer.completeError  (dart:async/future_impl.dart:30:5)
E/flutter ( 7039): #10     Future.any.<anonymous closure>  (dart:async/future.dart:464:45)
E/flutter ( 7039): #11     _rootRunBinary  (dart:async/zone.dart:1204:38)
E/flutter ( 7039): #12     _CustomZone.runBinary  (dart:async/zone.dart:1093:19)
E/flutter ( 7039): #13     _FutureListener.handleError  (dart:async/future_impl.dart:155:20)
E/flutter ( 7039): #14     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:694:47)
E/flutter ( 7039): #15     Future._propagateToListeners  (dart:async/future_impl.dart:715:24)
E/flutter ( 7039): #16     Future._completeError  (dart:async/future_impl.dart:534:5)
E/flutter ( 7039): #17     _AsyncAwaitCompleter.completeError  (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 7039): #18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 7039): <asynchronous suspension>
E/flutter ( 7039): #19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:849
E/flutter ( 7039): #20     DioMixin.checkIfNeedEnqueue 
package:dio/src/dio.dart:1117
E/flutter ( 7039): #21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> 
package:dio/src/dio.dart:846
E/flutter ( 7039): #22     new Future.<anonymous closure>  (dart:async/future.dart:176:37)
E/flutter ( 7039): #23     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter ( 7039): #24     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #25     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 7039): #26     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 7039): #27     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 7039): #28     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 7039): #29     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1003:23)
E/flutter ( 7039): #30     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7039): #31     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7039): #32     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7039): #33     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7039):
```

**Comment by eldadfux** [comment]
Hey! First of all, thank you for the great feedback ❤️.

About your issue, we have just pushed this SDK to Github ~2 days ago to test it against the dev version of Appwrite server. This SDK isn't designed to work with version 0.5.3 or lower of Appwrite.

We are working on this branch to add support for Flutter on the server-side:
https://github.com/appwrite/appwrite/tree/feature--flutter-support

Work on this is almost done, but we still need to add docs and tutorials on appwrite.io before merging to master and releasing a new version.

If you like to help with some beta-testing, I could help you setup the latest Appwrite version from the source-code. You can also reach out on our Discord channel, where we also share updates about flutter support progress. Discord invite URL is here: https://discord.gg/GSeTUeA

**Comment by salehahmedZ** [comment]
> If you like to help with some beta-testing, I could help you setup the latest Appwrite version from the source-code. 


Yes, that's would be great. Thanks
