### ISSUE TITLE
Unhandled Exception: PlatformException(CANCELED, User canceled login, null)

### ISSUE THREAD

**Issue by pedromassango** [appwrite/sdk-for-dart#3]
We receive `PlatformException` if we cancel the authentication process.

## Platform
- [x] Android

## Step to reproduce

1. Tap one of the auth button
2. when the system shows the app chooser dialog close it
3. note that the exception is thrown

Exception:

```
E/flutter ( 4056): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(CANCELED, User canceled login, null)
E/flutter ( 4056): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 4056): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 4056): <asynchronous suspension>
E/flutter ( 4056): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 4056): #3      FlutterWebAuth.authenticate (package:flutter_web_auth/flutter_web_auth.dart:35:27)
E/flutter ( 4056): #4      Account.createOAuth2Session (package:appwrite/services/account.dart:325:31)
E/flutter ( 4056): #5      PlaygroundState.build.<anonymous closure> (package:ftest/main.dart:86:24)
E/flutter ( 4056): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:930:19)
E/flutter ( 4056): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1017:38)
E/flutter ( 4056): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 4056): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
E/flutter ( 4056): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 4056): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 4056): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 4056): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 4056): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 4056): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 4056): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 4056): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 4056): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 4056): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 4056): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 4056): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 4056): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 4056): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 4056): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4056): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 4056): #26     _invoke1 (dart:ui/hooks.dart:281:10)
E/flutter ( 4056): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
E/flutter ( 4056): 

```

**Comment by eldadfux** [comment]
@pedromassango would be the expected behaviour for your scenario?

**Comment by eldadfux** [comment]
Closing this issue for now, we will reopen it if needed.

**Comment by pedromassango** [comment]
Hi @eldadfux 
Sorry, I currently don't remember what was the cause of this issue as it has been more than 8+ monthts for now. Let's keep it closed, I will come back to it if that happen with the latest version of the package.
Thanks
